### ISSUE TITLE
Error: Module not found when compile using Gideon.getInstance()

### ISSUE THREAD

**Issue by arpitnarechania** [tmdt-buw/gideon-replay#1]
Hi, I was trying to setup this cool utility but ran into an issue while trying to initialize the Gideon instance. 

I installed using 
`npm install @tmdt-buw/gideon-replay`,

imported in my component.ts using `import {Gideon} from "@tmdt-buw/gideon-replay";`, and

when I try to initialize it in my class using `gideon = Gideon.getInstance();`, it shows the below compilation errors associated with the resizer-observer-polyfill, lit-html, and lit packages.

<img width="1178" alt="Screenshot 2022-01-05 at 11 17 24 AM" src="https://user-images.githubusercontent.com/2376894/148251737-05593ae2-70a8-4a37-b5f3-cf115b3e984e.png">

I am using Angular 13.1.0 | Node v14.15.5 | NPM 6.4.11 | MacOS BigSur.

Looking forward to hearing from you.

**Comment by tfunken** [comment]
Thank you for the report! I will have a look at the issue in the coming days.

**Comment by tfunken** [comment]
I published v0.2.0 which should fix the issue. I tested the version of the library with Angular 13.

**Comment by arpitnarechania** [comment]
Thank you, no installation errors and the recording start-stop API is working. I ran into another rendering issue though, which I have described in [#2](https://github.com/tmdt-buw/gideon-replay/issues/2).
