### ISSUE TITLE
Colored Heatmap not getting rendered

### ISSUE THREAD

**Issue by arpitnarechania** [tmdt-buw/gideon-replay#2]
I installed v0.2.0 and followed the updated README and was able to start and stop the recording. However, the red, yellow, green colors of the HEATMAP don't show up. The playback window shows up, the mouse pointer moves correctly, but no colors. Checkout the below screenshot:

![quick-demo2](https://user-images.githubusercontent.com/2376894/149382682-4ab4cdf2-3db2-4ded-be30-b015fecc46cc.gif)

I looked up the above error and it pointed me to [an issue with heatmap.js](https://github.com/pa7/heatmap.js/issues/219). Now I am not sure if this is the issue since it seems quite old, plus, your demo is working just fine on my Chrome browser, i.e., colors do come up there. 

I wonder what's different between the packaged instance of Gideon-replay and the one that is being used in the demo?

**Comment by tfunken** [comment]
Thanks again for your effort to use our library. I accidentally switched to a bugged heatmap.js version. I released version 0.3.0 which uses a working version of heatmap.js. Also there is now the possibility to configure the heatmap itself:
https://github.com/tmdt-buw/gideon-replay#replay-user-interactions

**Comment by arpitnarechania** [comment]
Thanks for the prompt turnarounds! I didn't customize the heatmap (yet!) but I can confirm that this particular issue is fixed.
